services:
  db:
    image: postgres:16
    container_name: contratapp-db
    environment:
      POSTGRES_DB: contratapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - contratapp_pgdata:/var/lib/postgresql/data

volumes:
  contratapp_pgdata:
